backend:
  name: github
  repo: lucasjohnson/gatsby-netlify-cms-starter
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
site_url: https://gatsby-and.netlify.app/
display_url: https://gatsby-and.netlify.app/
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: posts
    label: Post
    folder: content/blog/
    create: true
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Date, name: date, widget: date }
      - label: Author
        name: author
        widget: 'relation'
        collection: 'authors'
        searchFields: [author.name, author.twitter]
        valueField: author.name
        displayFields: [author.twitter]
      - { label: Banner, name: banner, widget: image, allow_multiple: false }
      - { label: Alt Text, name: bannerAlt, widget: string }
      - {
          name: abstract,
          label: Abstract,
          widget: text,
          hint: Short description that will display under post title on Blog page,
          as well as being placed in the post meta data for SEO,
        }
      - {
          name: body,
          label: Body,
          widget: markdown,
          buttons: [bold, italic, link, heading-one, heading-two, heading-three, quote, bulleted-list, numbered-list],
        }
    editor:
      preview: true
  - name: site-data
    label: Site Data
    delete: false
    editor:
      preview: false
    files:
      - file: content/site/data.yml
        label: Site Data
        name: siteData
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site URL, name: siteUrl, widget: string }
          - { label: Site Description, name: siteDescription, widget: text, required: false }
          - { label: Site Author, name: siteAuthor, widget: string, required: false }
          - Label: Site Banner
            name: siteBanner
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
          - Label: Site Logo
            name: siteLogo
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
      - file: content/site/company.yml
        label: Company Details
        name: companyDetails
        fields:
          - { label: Street Address, name: companyStreetAddress, widget: string, required: false }
          - { label: City, name: companyCity, widget: string, required: false }
          - { label: Province, name: companyProvince, widget: string, required: false }
          - { label: Postal Code, name: companyPostalCode, widget: string, required: false }
          - { label: Country, name: companyCountry, widget: string, required: false }
          - { label: Telephone Number, name: companyTelephone, widget: string, required: false }
      - file: content/site/authors.yml
        label: Authors
        name: authors
        fields:
          - label: Author
            name: author
            collapsed: false
            minimize_collapsed: false
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Email, name: email, widget: string, required: false }
              - { label: Twiiter Handle, name: url, widget: string, required: false }
              - { label: Website, name: website, widget: string, required: false }
      - file: content/site/services.yml
        label: Services
        name: services
        fields:
          - label: Service
            name: service
            collapsed: false
            minimize_collapsed: false
            widget: list
            fields:
              - { label: Service Name, name: name, widget: string }
      - file: content/site/topics.yml
        label: Topics
        name: topics
        fields:
          - label: Topic
            name: topic
            collapsed: false
            minimize_collapsed: false
            widget: list
            fields:
              - { label: Topic Name, name: name, widget: string }
      - file: content/site/social.yml
        label: Social Media Account
        name: socialMediaAccounts
        fields:
          - { label: Business Twitter Handle, name: twitterHandle, widget: string, required: false }
          - label: Social Media Account
            name: socialMediaAccounts
            collapsed: false
            minimize_collapsed: false
            widget: list
            summary: '{{fields.type}}s'
            fields:
              - { label: Type, name: type, widget: string }
              - { label: URL, name: url, widget: string }
