backend:
  name: github
  repo: lucasjohnson/gatsby-netlify-cms-starter

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - name: posts
    label: Post
    folder: content/posts/
    create: true
    slug: '{{slug}}'
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: banner, label: Banner, widget: image, allow_multiple: false }
      - {
          name: abstract,
          label: Abstract,
          widget: text,
          hint: 'Short description that will display under post title on Blog page, as well as being placed in the post meta data for SEO',
        }
      - {
          name: body,
          label: Body,
          widget: markdown,
          buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'quote', 'bulleted-list', 'numbered-list'],
          hint: 'Do not add image to this editor, it will not display if you do.',
        }
    editor:
      preview: true
  - name: site_data
    label: 'Site Data'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/site/data.yml'
        label: 'Site Data'
        name: 'siteData'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site URL, name: siteUrl, widget: string }
          - { label: Site Description, name: siteDescription, widget: text, required: false }
          - { label: Site Author, name: siteAuthor, widget: string, required: false }
          - Label: 'Site Banner'
            name: siteBanner
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
          - Label: 'Site Logo'
            name: siteLogo
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
      - file: 'content/site/social.yml'
        label: 'Social Media Accounts'
        name: 'socialMediaAccounts'
        fields:
          - { label: Twitter Handle, name: twitterHandle, widget: string, required: false }
          - label: 'Social Media Accounts'
            name: 'socialMediaAccounts'
            minimize_collapsed: true
            widget: 'list'
            summary: '{{fields.type}}: {{fields.url}}'
            fields:
              - { label: Type, name: type, widget: string }
              - { label: URL, name: url, widget: string }
      - file: 'content/site/business.yml'
        label: 'Business Details'
        name: 'businessDetails'
        fields:
          - { label: Street Address, name: businessStreet, widget: string, required: false }
          - { label: City, name: businessCity, widget: string, required: false }
          - { label: Province, name: businessProvince, widget: string, required: false }
          - { label: Postal Code, name: businessPostalCode, widget: string, required: false }
          - { label: Country, name: businessCountry, widget: string, required: false }
          - { label: Telephone Number, name: businessTelephone, widget: string, required: false }
