backend:
  name: github
  repo: lucasjohnson/gatsby-netlify-cms-starter
media_folder: static/assets
public_folder: /assets
site_url: https://gatsby-and.netlify.app/
display_url: https://gatsby-and.netlify.app/
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: posts
    label: Post
    folder: content/blog/
    create: true
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Pathname, name: path, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Author, name: author, widget: relation, collection: authors, searchFields: [name], valueField: name }
      - {
          label: Topics,
          name: topics,
          widget: relation,
          collection: topics,
          searchFields: [name],
          valueField: name,
          multiple: true,
        }
      - { label: Banner, name: banner, widget: image, allow_multiple: false }
      - { label: Alt Text, name: bannerAlt, widget: string }
      - {
          name: abstract,
          label: Abstract,
          widget: text,
          hint: Short description that will display under post title on Blog page,
          as well as being placed in the post meta data for SEO,
        }
      - {
          name: body,
          label: Body,
          widget: markdown,
          buttons: [bold, italic, link, heading-one, heading-two, heading-three, quote, bulleted-list, numbered-list],
        }
  - label: Authors
    name: authors
    folder: content/authors/
    create: true
    editor:
      preview: false
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Email, name: email, widget: string, required: false }
      - { label: Twitter Handle, name: twitter, widget: string, required: false }
      - { label: Website, name: website, widget: string, required: false }
  - label: Services
    name: services
    folder: content/services/
    create: true
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Related Topics,
          name: topics,
          widget: relation,
          collection: topics,
          searchFields: [name],
          valueField: name,
          multiple: true,
          required: false,
        }
      - {
          name: abstract,
          label: Abstract,
          widget: text,
          hint: Short description that will display under post title on Blog page,
          as well as being placed in the post meta data for SEO,
          required: false,
        }
      - {
          name: body,
          label: Body,
          widget: markdown,
          required: false,
          buttons: [bold, italic, link, heading-one, heading-two, heading-three, quote, bulleted-list, numbered-list],
        }
  - label: Topics
    name: topics
    folder: content/topics/
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - { label: Tag Name, name: name, widget: string }
  - name: site-data
    label: Site Data
    delete: false
    editor:
      preview: false
    files:
      - file: content/site/data.yml
        label: Site Data
        name: siteData
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site URL, name: siteUrl, widget: string }
          - { label: Site Description, name: siteDescription, widget: text, required: false }
          - { label: Site Author, name: siteAuthor, widget: string, required: false }
          - Label: Site Banner
            name: siteBanner
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
          - Label: Site Logo
            name: siteLogo
            widget: object
            required: false
            fields:
              - { label: Image, name: image, widget: image, required: false }
              - { label: Alt Text, name: imageAlt, widget: string, required: false }
      - file: content/site/company.yml
        label: Company Details
        name: companyDetails
        fields:
          - { label: Street Address, name: companyStreetAddress, widget: string, required: false }
          - { label: City, name: companyCity, widget: string, required: false }
          - { label: Province, name: companyProvince, widget: string, required: false }
          - { label: Postal Code, name: companyPostalCode, widget: string, required: false }
          - { label: Country, name: companyCountry, widget: string, required: false }
          - { label: Telephone Number, name: companyTelephone, widget: string, required: false }
      - file: content/site/social.yml
        label: Social Media Account
        name: socialMediaAccounts
        fields:
          - { label: Business Twitter Handle, name: twitterHandle, widget: string, required: false }
          - label: Social Media Account
            name: socialMediaAccounts
            collapsed: false
            minimize_collapsed: false
            widget: list
            summary: '{{fields.type}}s'
            fields:
              - { label: Type, name: type, widget: string }
              - { label: URL, name: url, widget: string }
